version: "3"

services:
  main:
    container_name: node_app
    env_file:
      - .env
    volumes:
    - uploaddata:/var/app/upload
    environment:
      NODE_ENV: production
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
volumes:
  dbdata:
  uploaddata:
